font_family Iosevka SS04
font_size 11

shell_integration disabled

copy_on_select clipboard
cursor_beam_thickness 2
cursor_blink_interval 0
cursor_shape beam
disable_ligatures always
draw_minimal_borders yes
enable_audio_bell no
enabled_layouts all
hide_window_decorations yes
linux_display_server wayland
mouse_hide_wait -1
scrollback_lines 9001
scrollback_pager_history_size 2048
strip_trailing_spaces smart
tab_bar_edge bottom
tab_bar_margin_width 0
tab_bar_min_tabs 1
tab_bar_style separator
tab_separator  |
tab_title_max_length 16
tab_title_template  {index}: {title}{activity_symbol}
undercurl_style thin-sparse
update_check_interval 1
visual_bell_duration 0

background #0f1014
foreground #868690
cursor #c58fff
selection_background #817c9c
selection_foreground #868690
color0 #131317
color1 #f58ee0
color2 #8eb6f5
color3 #9898a6
color4 #c58fff
color5 #fdfdfe
color6 #ffbb88
color7 #868690
color8 #575861
color9 #f58ee0
color10 #8eb6f5
color11 #9898a6
color12 #c58fff
color13 #fdfdfe
color14 #ffbb88
color15 #868690

active_tab_foreground #868690
active_tab_background #0f1014
active_tab_font_style bold
inactive_tab_foreground #868690
inactive_tab_background #0f1014

clear_all_shortcuts true
map_timeout 1.0

map cmd+c copy_or_noop
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+a>ctrl+p command_palette
map ctrl+a>ctrl+end scroll_end
map ctrl+a>ctrl+home scroll_home
map ctrl+a>ctrl+up scroll_line_up
map ctrl+a>ctrl+down scroll_line_down
map ctrl+a>ctrl+page_up scroll_line_page_up
map ctrl+a>ctrl+page_down scroll_line_page_down
map ctrl+a>ctrl+w close_tab
map ctrl+a>ctrl+t new_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
