"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$nix_shell\
$character"""

[palettes.moonlight_dark]
background = "#0f1014"
current_line = "#111216"
foreground = "#868690"
comment = "#43444d"
cyan = "#f58ee0"
green = "#c58fff"
orange = "#ffbb88"
pink = "#ffbb88"
purple = "#9898a6"
red = "#f58ee0"
yellow = "#8eb6f5"

[directory]
style = "cyan"

[character]
success_symbol = "[~](purple)"
error_symbol = "[~](red)"
vimcmd_symbol = "[~](green)"

[git_branch]
format = "[$branch]($style)"
style = "purple"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = "*"
staged = "✓"
renamed = ""
deleted = "✗"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nix_shell]
symbol = " "
heuristic = true
