[buildPlans.IosevkaPippin]
family = "Iosevka Pippin"
spacing = "normal"
serifs = "sans"
exportGlyphNames = true
noLigation = true
buildTextureFeature = true

[buildPlans.IosevkaPippin.variants]
inherits = "ss04"

[buildPlans.IosevkaPippin.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaPippin.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaPippin.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaPippin.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaPippin.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaPippin.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaPippin.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaPippin.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaPippin.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaPippin.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaPippin.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaPippin.widths.ExtraCondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.IosevkaPippin.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaPippin.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaPippin.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaMerry]
family = "Iosevka Merry"
spacing = "term"
serifs = "sans"
exportGlyphNames = true
noLigation = true
buildTextureFeature = true

[buildPlans.IosevkaMerry.variants]
inherits = "ss04"

[buildPlans.IosevkaMerry.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaMerry.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaMerry.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaMerry.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaMerry.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaMerry.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaMerry.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaMerry.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaMerry.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaMerry.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaMerry.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaMerry.widths.ExtraCondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.IosevkaMerry.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaMerry.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaMerry.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaHatahata]
family = "Iosevka Hatahata"
spacing = "fontconfig-mono"
serifs = "sans"
exportGlyphNames = true
noLigation = true
buildTextureFeature = true

[buildPlans.IosevkaHatahata.variants]
inherits = "ss04"

[buildPlans.IosevkaHatahata.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaHatahata.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaHatahata.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaHatahata.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaHatahata.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaHatahata.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaHatahata.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaHatahata.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaHatahata.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaHatahata.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaHatahata.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaHatahata.widths.ExtraCondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.IosevkaHatahata.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaHatahata.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaHatahata.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaCoco]
family = "Iosevka Coco"
spacing = "quasi-proportional"
serifs = "sans"
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.IosevkaCoco.variants.design]
capital-i = "serifless"
capital-j = "serifless"
capital-k = "straight-serifless"
capital-m = "flat-bottom-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-serifless"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "serifless"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-flat-top-serifless"
y = "straight-serifless"
long-s = "flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
lower-tau = "flat-tailed"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-connected-serifless"
cyrl-em = "flat-bottom-serifless"
cyrl-capital-u = "straight-serifless"
cyrl-u = "straight-serifless"
cyrl-ef = "serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"
at = "fourfold"
percent = "rings-continuous-slash"
micro-sign = "toothed-serifless"

[buildPlans.IosevkaCoco.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaCoco.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCoco.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCoco.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCoco.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCoco.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCoco.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaCoco.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaCoco.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaCoco.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCoco.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaCoco.widths.ExtraCondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.IosevkaCoco.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCoco.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCoco.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaWhiskeyKazumi]
family = "Iosevka Whiskey Kazumi"
spacing = "quasi-proportional"
serifs = "slab"
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.IosevkaWhiskyKazumi.variants.design]
capital-m = "flat-bottom-serifed"
capital-w = "straight-flat-top-serifed"
f = "flat-hook-serifed"
i = "serifed"
j = "flat-hook-serifed"
l = "serifed"
t = "flat-hook"
w = "straight-flat-top-serifed"
long-s = "flat-hook-bottom-serifed"
eszet = "longs-s-lig-bottom-serifed"
lower-iota = "serifed-flat-tailed"
lower-tau = "flat-tailed"
cyrl-em = "flat-bottom-serifed"
at = "fourfold"
percent = "rings-continuous-slash"

[buildPlans.IosevkaWhiskyKazumi.variants.italic]
f = "flat-hook-tailed"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
w = "straight-flat-top-motion-serifed"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"

[buildPlans.IosevkaWhiskyKazumi.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaWhiskyKazumi.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaWhiskyKazumi.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaWhiskyKazumi.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaWhiskyKazumi.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaWhiskyKazumi.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaWhiskyKazumi.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaWhiskyKazumi.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaWhiskyKazumi.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaWhiskyKazumi.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaWhiskyKazumi.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaWhiskyKazumi.widths.ExtraCondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.IosevkaWhiskyKazumi.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaWhiskyKazumi.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaWhiskyKazumi.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[collectPlans.IosevkaPippin]
from = [
  "IosevkaPippin"
]

[collectPlans.IosevkaMerry]
from = [
  "IosevkaMerry"
]

[collectPlans.IosevkaHatahata]
from = [
  "IosevkaHatahata"
]

[collectPlans.IosevkaCoco]
from = [
  "IosevkaCoco"
]

[collectPlans.IosevkaWhiskeyKazumi]
from = [
  "IosevkaWhiskeyKazumi"
]
